title: dtc innovation
tag_text: dtc innovation
description: Designing Technology for the Commons.
baseurl: ""
url: https://dtc-innovation.org

permalink: /writings/:year/:title

collections:
  projects:
    output: true
    permalink: /projects/:title
    resources:
      github: GitHub Project
      website: Website
  assemblies:
    output: true
    permalink: /dna/assemblies/:slug.html


company:
  siren: '823553557'
  siret: '82355355700013'
  vat: 'FR67823553557'
  rna: 'W332020707'
  ape: '6201Z'
  since: 2016-09-16

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "writing"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "assemblies"
    values:
      layout: "page"

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
  - jekyll-feed
