title: dtc innovation
tag_text: dtc innovation
description: >
  We design, prototype and engineer innovation for the web and for the commons.
url: "http://127.0.0.1:4000"
baseurl: ""

font-awesome-include: false

# Build settings
markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
