---
---

backend:
  name: github
  repo: dtc-innovation/dtc-innovation.github.io
  branch: master

media_folder: "images/uploads"
publish_mode: editorial_workflow

collections:
  - name: "writing"
    label: "Writings"
    folder: "_posts"
    sort: "date:desc"
    create: true
    slug: "{% raw %}{{year}}-{{month}}-{{day}}-{{slug}}{% endraw %}"
    fields:
      - label: "Title"
        name: "title"
        tagname: "h1"
        widget: "string"
      - label: "Subtitle"
        name: "subtitle"
        tagname: "h2"
        widget: "string"
        required: false
      - label: "Writing Body"
        name: "body"
        widget: "markdown"
      - label: "Cover image"
        name: image
        widget: "image"
        required: false
      - label: "Language"
        name: "lang"
        widget: "select"
        options: ["", "fr", "en"]
        required: false
      - label: "Categories"
        name: "category"
        widget: "string"
        required: false
      - label: "Linked Project"
        name: "projects"
        widget: "select"
        options: ["", {% for d in site.projects %}{{ d.slug | jsonify }},{% endfor %}]
        required: false
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD hh:mm:ss"
  - name: "project"
    label: "Projects"
    folder: "_projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - label: "Name"
        name: "name"
        widget: "string"
        tagname: "h1"
      - label: "Short Description"
        name: "short_description"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Cover image"
        name: image
        widget: "image"
        required: false
      - label: "Customer"
        name: "customer"
        widget: "select"
        options: ["", {% for d in site.data.customers %}{{ d[0] | jsonify }},{% endfor %}]
        required: false
      - label: "Labels"
        name: "labels"
        widget: "list"
        required: false
      - label: "Highlight Order"
        name: "highlights_order"
        widget: "number"
        required: false
      - label: "Current Stage"
        name: "current_stage"
        widget: "string"
        required: false
      - label: "Next Stage"
        name: "next_stage"
        widget: "string"
        required: false
      - label: "Resources"
        name: "resources"
        widget: "object"
        required: false
        fields:
          - label: "GitHub"
            name: "github"
            widget: "string"
            required: false
          - label: "Website"
            name: "website"
            widget: "string"
            required: false
